language: vi   # Ngôn ngữ tiếng Việt

pipeline:
- name: WhitespaceTokenizer
    # split sentence by white space

- name: RegexFeaturizer


- name: LexicalSyntacticFeaturizer


- name: CountVectorsFeaturizer


- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4

- name: DIETClassifier
    #  Dual Intent and Entity Transformer (get user intention by all sentence not by word)
  epochs: 100


- name: EntitySynonymMapper


- name: ResponseSelector
  epochs: 100

- name: FallbackClassifier
    # can't recognize user intent
  threshold: 0.3
  ambiguity_threshold: 0.1

policies:
  # remember all conversations
- name: MemoizationPolicy

  #Model convert conversation
- name: TEDPolicy
  max_history: 5
  epochs: 100

- name: RulePolicy
assistant_id: 20250429-220610-serious-moat
